export enum CacheObject {
    TALENT_MANAGEMENT_FN_MACHINE_TOKEN = 'TALENT_MANAGEMENT_FN:MACHINE_TOKEN',
    COMPANY_LOOKUP = 'COMPANY_LOOKUP',
    COMPANY_ID = 'COMPANY:COMPANY_ID',
    FIT_SCORE_RECIPE_ID = 'FIT_SCORE_RECIPE:RECIPE_ID',
}

export enum CacheTtl {
    DEFAULT = 43200, // 12 hours
}
