export enum EmployeeScoreType {
    ROLE_FIT = 'role_fit',
    CULTURE_FIT = 'culture_fit',
    // SKILL = 'competency_skill',
    // COMPETENCY_EXP = 'competency_experience',
    REASONING_LOGICAL = 'reasoning_logical',
    REASONING_NUMERIC = 'reasoning_numeric',
    REASONING_VERBAL = 'reasoning_verbal',
    REASONING_AVG = 'reasoning_average',
    WORK_STYLE = 'work_style',
    WORK_VALUE = 'work_value',
    WORK_INTEREST = 'work_interest',
    HARD_SKILL = 'hard_skill',
    WORK_EXP = 'work_experience',
    PERSONALITY = 'personality',
    REASONING_LOGIC = 'reasoning_logic',
}
