export enum DomainEventType {
    EMPLOYEE_REMINDER = 'talent_management_employee_reminder',
    MANAGER_WEEKLY_SUBORDINATE_PROGRESS_REPORT = 'talent_management_manager_weekly_subordinate_progress_report',
    EMPLOYEE_FEEDBACK_NOMINATION_REQUESTED = 'talent_management_feedback_nomination_requested',
    MANAGER_FEEDBACK_NOMINATION_APPROVAL_REQUESTED = 'talent_management_feedback_manager_nomination_approval_requested',
    FEEDBACK_NOMINATION_SUBMISSION_DUE = 'talent_management_feedback_nomination_submission_due',
    FEEDBACK_MANAGER_NOMINATION_APPROVAL_DUE = 'talent_management_feedback_manager_nomination_approval_due',
    FEEDBACK_REVIEWEE_RESPONSE_SUBMISSION_DUE = 'talent_management_feedback_reviewee_response_submission_due',
    FEEDBACK_REVIEWER_RESPONSE_SUBMISSION_DUE = 'talent_management_feedback_reviewer_response_submission_due',
    FEEDBACK_NOMINATION_APPROVED = 'talent_management_feedback_nomination_approved',
    FEEDBACK_NOMINATION_AMENDMENT_APPROVED = 'talent_management_feedback_nomination_amendment_approved',
    FEEDBACK_MANAGER_NOMINATION_AUTO_APPROVED = 'talent_management_feedback_manager_nomination_auto_approved',
    FEEDBACK_REVIEWEE_RESPONSE_REQUESTED = 'talent_management_feedback_reviewee_response_requested',
    FEEDBACK_REVIEWER_RESPONSE_REQUESTED = 'talent_management_feedback_reviewer_response_requested',
    FEEDBACK_REVIEWEE_RESULT_READY = 'talent_management_feedback_reviewee_result_ready',
    FEEDBACK_MANAGER_DIRECT_REPORT_RESULT_READY = 'talent_management_feedback_manager_direct_report_result_ready',
    FEEDBACK_REVIEWEE_FEEDBACK_RECOMMENDATION_COMPLETED = 'talent_management_feedback_reviewee_recommendation_completed',
    PARTICIPANT_PROGRAM_RESULT_READY = 'talent_management_employee_program_result_ready',
    EMPLOYEE_ASSESSMENTS_SCORE_CALCULATED = 'talent_management_assessments_score_calculated',
}
