name: Deploy to Env
on:
    pull_request:
        types: [labeled]

    workflow_dispatch:
        inputs:
            environment:
                required: true
                description: Environment to deploy
                default: sandbox
                type: environment
            ref:
                required: false
                type: string
                description: The branch, tag or SHA to git checkout

jobs:
    input-check:
        if: ${{ (github.event_name == 'workflow_dispatch') || (github.event.label.name == 'sandbox deploy') }}
        runs-on: ubuntu-latest
        outputs:
            environment: ${{ steps.input-check.outputs.environment }}
        steps:
            - uses: Pulsifi/github-template/environment-input-check@master
              id: input-check
              with:
                  environment: ${{ inputs.environment }}

    deploy-to-env:
        needs: [input-check]
        permissions:
            id-token: write
            contents: read
        uses: ./.github/workflows/wc-deploy-to-env.yml
        with:
            environment: ${{ needs.input-check.outputs.environment }}
            ref: ${{ inputs.ref }}
        secrets: inherit
